testnetName: testnet
mina:
  image: minaprotocol/mina-daemon:9faad06-focal-berkeley
  privkeyPass:
  exposeGraphql: true
  seedPeers:
    - /dns4/seed1/tcp/10909/p2p/12D3KooWBT8pyJAfWJhdeGYAtKvcaUmm78ExyZ6uo6BEimYNVat1
  # memRequest: 4Gi
  # cpuRequest: 4


frontend:
  image: directcuteo/mina-frontend:resources2
  nodePort: 31315
  nodes: [ "seed1", "prod1", "prod2", "node1", "node2", "node3", "node4", "snark-coordinator" ]

healthcheck:
  enabled: false
  failureThreshold: 60
  periodSeconds: 10
  initialDelaySeconds: 60

plainNodesConfig:
  count: 4
  namePrefix: node

seedConfigs:
  - name: seed1
    libp2pSecret: seed1-libp2p-secret

blockProducerConfigs:
  - name: prod1
    privateKeySecret: prod1-privkey-secret
    isolated: false
  - name: prod2
    privateKeySecret: prod2-privkey-secret
    isolated: false

resources:
  enable: true
  image: adrnagy/mina-node-monitoring:17c9127
  args: ["--executable-name=mina"]

bpfDebugger:
  enable: true
  image: akoptelov/mina-network-debugger:bef771e
  chainId: f8eecad2443cd48f1a74a087257cac9fe052f2af5bbd1666d967e47104228fb0

nodeSelector:
  preemptible: false

