testnetName: testnet
mina:
  image: minaprotocol/mina-daemon:9faad06-focal-berkeley
  privkeyPass:
  exposeGraphql: true
  seedPeers:
    - /dns4/seed1/tcp/10909/p2p/12D3KooWBT8pyJAfWJhdeGYAtKvcaUmm78ExyZ6uo6BEimYNVat1
frontend:
  image: directcuteo/mina-frontend:scstate12
  nodePort: 31313
  nodes: [ "seed1", "prod1", "prod2", "node1", "node2", "node3" ]

healthcheck:
  enabled: false
  failureThreshold: 60
  periodSeconds: 10
  initialDelaySeconds: 60

plainNodesConfig:
  count: 3

seedConfigs:
  - name: seed1
    libp2pSecret: seed1-libp2p-secret

blockProducerConfigs:
  - name: prod1
    privateKeySecret: prod1-privkey-secret
    isolated: false
  - name: prod2
    privateKeySecret: prod2-privkey-secret
    isolated: false

nodeSelector:
  preemptible: false

