name: Mina Testnet Deployment
run-name: Deploys a test network using latest Mina docker image
on:
  push:
  schedule:
    # daily at 5:00 UTC
    - cron: '0 5 * * *'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get Latest Mina Tag
        id: get-tag
        run: |
          URL="https://hub.docker.com/v2/namespaces/minaprotocol/repositories/mina-daemon/tags?page_size=25"
          JQ='.results | sort_by(.last_updated) | .[] | select(.name | endswith("focal-berkeley")) | .name'
          TAG=$(curl -s "$URL" | jq -cr "$JQ" | head -n 1)
          [ -n "$TAG" ] || { echo "Cannot get latest focal-berkeley tag"; exit 1; }
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - run: echo "Using minaprotocol/mina-daemon:${{ steps.get-tag.outputs.tag }}"

      - name: Checkout Mina
        uses: actions/checkout@v3
        with:
          repository: name-placeholder/mina
          ref: helm-opemnima-additions
          path: mina

      - name: Configure Helm
        env:
          KUBECONFIG_CONTENT: ${{secrets.KUBECONFIG}}
        run: |
          umask 0077
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG_CONTENT" > $HOME/.kube/config
          kubectl config set-context --current --namespace ${NAMESPACE:-mina-testnet}

      - name: Deploy Testnet
        env:
          HELM_ARGS: |
            --install
            --values=values.yaml
            --set-file=mina.runtimeConfig=resources/daemon.json
            --set=mina.image=minaprotocol/mina-daemon:${{ steps.get-tag.outputs.tag }}
        run: |
          cat values.yaml
          helm upgrade --install seeds mina/helm/seed-node $HELM_ARGS
          helm upgrade --install producers mina/helm/block-producer $HELM_ARGS
          helm upgrade --install snark-worker mina/helm/snark-worker/ $HELM_ARGS --set-file=publicKey=resources/key-05.pub
          helm upgrade --install nodes mina/helm/plain-node/ $HELM_ARGS
          helm upgrade --install frontend mina/helm/openmina-frontend $HELM_ARGS
